### ISSUE TITLE
Populus tutorial

### ISSUE THREAD

**Issue by avatar-lavventura** [avatar-lavventura/ethereum#4]
`Populus` is a smart contract development framework for the Ethereum blockchain.

In addition, populus needs some system dependencies to be able to install the [PyEthereum](https://github.com/ethereum/pyethereum/) library:
```
[~] git clone https://github.com/ethereum/pyethereum/
[~] cd pyethereum
[~] python setup.py install
```

Install `Populus` from the following guide in the [link](http://populus.readthedocs.io/en/latest/quickstart.html): 

Do following:
`[~] sudo pip install py-solc==0.6.0`

**Initializing a new project:**
```
[~] mkdir populus_workspace && cd populus_workspace

[~/populus_workspace] populus init
Created Directory: ./contracts
Created Example Contract: ./contracts/Greeter.sol
Created Directory: ./tests
Created Example Tests: ./tests/test_greeter.py

[~/populus_workspace] cat contracts/Greeter.sol
contract Greeter {
    string public greeting;

    function Greeter() {
        greeting = 'Hello';
    }

    function setGreeting(string _greeting) public {
        greeting = _greeting;
    }

    function greet() constant returns (string) {
        return greeting;
    }
}

[~/populus_workspace] cat tests/test_greeter.py
def test_greeter(chain):
    greeter = chain.get_contract('Greeter')

    greeting = greeter.call().greet()
    assert greeting == 'Hello'


def test_custom_greeting(chain):
    greeter = chain.get_contract('Greeter')

    set_txn_hash = greeter.transact().setGreeting('Guten Tag')
    chain.wait.for_receipt(set_txn_hash)

    greeting = greeter.call().greet()
    assert greeting == 'Guten Tag'
    print(greeting);  #added later.

[~/populus_workspace] py.test --capture=fd tests/test_greeter.py -s
===================================== test session starts =====================================
platform darwin -- Python 2.7.13, pytest-3.0.5, py-1.4.32, pluggy-0.4.0
rootdir: /Users/alper/den, inifile:
plugins: populus-1.4.2
collected 2 items
.Guten Tag
.
================================== 2 passed in 1.52 seconds ===================================

**Comment by ktasyaran** [comment]
I installed populus but it gives that when I write populus init in populus_workspace:

AttributeError: module 'anyconfig' has no attribute 'to_container'

**Comment by avatar-lavventura** [comment]
`python -V ` ne donduruyor?@ktasyaran

**Comment by avatar-lavventura** [comment]
I have updated the installation on the guide I guess you were using mac, can you try this: `brew install pkg-config libffi autoconf automake libtool openssl` @ktasyaran

**Comment by ktasyaran** [comment]
python -V returns python 2.7.10 @avatar-lavventura. Does it make a difference?
And I realized that it won't work on solidity 0.4.9. And finally, what is a difference between pyethapp and pyethereum?

**Comment by avatar-lavventura** [comment]
I am working on the revert solc 0.4.9 to 0.4.8 but having some problems to fix it. https://github.com/pipermerriam/populus/issues/266 @ktasyaran

**Comment by avatar-lavventura** [comment]
pyethapp vs pyethereum: http://ethereum.stackexchange.com/questions/5769/whats-the-difference-between-pyethapp-and-pyethereum @ktasyaran

**Comment by ktasyaran** [comment]
I tried now. I realized that you do not have to install solidity via downloading tar for mac users who use Homebrew. It holds both 0.4.8 and 0.4.9 for now. Also populus did not accept with web3 3.5.2 after writing populus init. It wanted 3.7.1. I tried with 3.7.1 and it passed tests.

**Comment by avatar-lavventura** [comment]
Did you just done `brew install solidity`? @ktasyaran

**Comment by ktasyaran** [comment]
brew install solidity gives latest which is 0.4.9. 

For 0.4.8, you need to do this:
brew install https://raw.githubusercontent.com/ethereum/homebrew-ethereum/77cce03da9f289e5a3ffe579840d3c5dc0a62717/solidity.rb

**Comment by avatar-lavventura** [comment]
Thanks, I added that to installation guide. @ktasyaran

**Comment by avatar-lavventura** [comment]
Did you updated the SOLC_BINARY, LD_LIBRARY_PATH and PATH? @ktasyaran

**Comment by ktasyaran** [comment]
No. Just installed with command written above. Still I can run solidity anywhere in my computer. Therefore, I didn't update paths. I think this path adjustments running solidity globally instead of build folder. Am I wrong?

**Comment by avatar-lavventura** [comment]
What does `solc --version `returns?

**Comment by ktasyaran** [comment]
Version: 0.4.8+commit.60cc1668.Darwin.appleclang

**Comment by avatar-lavventura** [comment]
Great, your system overwritten 04.8 onto 0.4.9 that's why you didn't have to update the paths. On ubuntu it require some additional work to do in order to target build folder for 0.4.8.

**Comment by ktasyaran** [comment]
Also, cmake sometimes may not build solidity 
for this --recursive option can be used.
git clone --recursive https://github.com/ethereum/solidity.git

**Comment by ebloc** [comment]
This issue was moved to ebloc/eBloc#4
